// Generated by CoffeeScript 1.8.0
(function() {
  var coffee, cssmin, gulp, paths, prefix, rjs, runSequence, sass, sourcemaps;

  gulp = require('gulp');

  runSequence = require('run-sequence');

  sourcemaps = require('gulp-sourcemaps');

  coffee = require('gulp-coffee');

  sass = require('gulp-sass');

  prefix = require('gulp-autoprefixer');

  cssmin = require('gulp-cssmin');

  rjs = require('requirejs');

  paths = {
    coffee: './coffeescript/**/*.coffee',
    sass: './sass/**/*.scss'
  };

  gulp.task('default', function(reportTaskDone) {
    gulp.watch(paths.coffee, ['build-scripts']);
    gulp.watch(paths.sass, ['build-styles']);
    return runSequence(['build-scripts', 'build-styles'], reportTaskDone);
  });

  gulp.task('coffee', function() {
    return gulp.src(paths.coffee).pipe(sourcemaps.init()).pipe(coffee()).pipe(sourcemaps.write('../maps/')).pipe(gulp.dest('./javascript/'));
  });

  gulp.task('build-scripts', function(reportTaskDone) {
    return runSequence('coffee', 'requirejs', reportTaskDone);
  });

  gulp.task('build-styles', function() {
    return gulp.src(paths.sass).pipe(sass()).pipe(prefix('> 1%')).pipe(cssmin({
      keepSpecialComments: 0
    })).pipe(gulp.dest('./'));
  });

  gulp.task('requirejs', function(reportTaskDone) {
    var requirejsOptions;
    requirejsOptions = {
      baseUrl: './javascript',
      optimize: 'uglify2',
      preserveLicenseComments: false,
      generateSourceMaps: true,
      name: 'tictactoe',
      out: './tictactoe-min.js',
      paths: {
        jquery: '../bower_components/jquery/dist/jquery',
        three: '../bower_components/threejs/build/three'
      },
      shim: {
        three: {
          exports: 'THREE'
        }
      }
    };
    rjs.optimize(requirejsOptions);
    return reportTaskDone();
  });

}).call(this);
