define ->
  NO_WEBGL: 'no-webgl'
  HELP: 'help'
  POSSIBLE_MOVE: 'possible-move'
  TENTATIVE_MOVE: 'tentative-move'
  THINKING: 'thinking'
  END_GAME: 'endgame'
  PLAYER_WIN: 'player-win'
  COMPUTER_WIN: 'computer-win'
  DRAW: 'draw',
  READY_TO_RESET: 'ready-to-reset'
